create table test (
  id bigint generated by default as identity primary key,
  name text,
  created_at timestamptz default now()
);

create policy "test_policy"
on "public"."test"
as PERMISSIVE
for ALL
to anon
using (
  true
);